United States of America:
  N/A:
  
  # Federal Positions
  President:
    level: "federal"
  Vice President:
    level: "federal"
  Supreme Court Justice:
    level: "federal"
    
  # State Positions
  Governor:
    level: "state"
  Lieutenant Governor:
    level: "state"
  Attorney General:
    level: "state"
  Secretary of State:
    level: "state"
  General Treasurer:
    level: "state"
  Senator:
    level: "state"
  U.S. Representative:
    level: "state"
    
  # County Positions
  Sheriff:
    level: "county"
  
  # Local Positions
  State Senator:
    level: "local"
  State Representative:
    level: "local"
    
  # Town Positions
  Town Counselor:
    level: "town"
  Selectman:
    level: "town"
  
  # City Positions
  City Counselor:
    level: "city"
  Mayor:
    level: "city"
  School Committee:
    level: "city"
    
Canada:
  N/A:
  
  # Federal Positions
  Monarch:
    level: "federal"
  Member of Parliament:
    level: "federal"
  Prime Minister:
    level: "federal"
  Governor General:
    level: "federal"
  Supreme Court Justice:
    level: "federal"
  Senator:
    level: "federal"
    
  # Provincial Positions
  Member of Provincial Parliament:
    level: "provincial"
  Member of the National Assembly:
    level: "provincial"
  Member of the House of Assembly:
    level: "provincial"
  Member of the Legislative Assembly:
    level: "provincial"
  Premier:
    level: "provincial"
  
  # City Positions
  Mayor:
    level: "city"
  
