"AB":
  name: Alberta

"BC":
  name: British Columbia
  
"MB":
  name: Manitoba
  
"NB":
  name: "New Brunswick"
  
"NL":
  name: "Newfoundland and Labrador"
  
"NS":
  name: "Nova Scotia"

"ON":
  name: "Ontario"

"PE":
  name: "Prince Edward Island"
  
"QA":
  name: "Quebec"
  
"SK":
  name: "Saskatchewan"
  
"NT":
  name: "Northwest Territories"
  
"NU":
  name: "Nunavut"
  
"YK":
  name: "Yukon"